import type { PrismaClient } from "../generated/prisma/client";
import { offsetDate } from "./seed-support";

export async function seedProposals(prisma: PrismaClient, now: Date, year: number) {
  await prisma.commercialProposal.upsert({
    where: { id: "seed_proposal_sanitary_v1" },
    update: {
      proposalNumber: `КП-${year}-0001`,
      dealId: "seed_deal_apartments_sanitary",
      clientId: "seed_client_showroom",
      objectId: "seed_project_object_apartments",
      designerId: "seed_designer_north",
      responsibleId: "seed_owner",
      version: 1,
      parentProposalId: null,
      amount: 1850000,
      discountPercent: 7,
      discountAmount: 139250,
      status: "SENT",
      recipientType: "CLIENT",
      recipientName: "Клиент шоурума",
      recipientContact: "client@example.com",
      approvalRequiredFrom: "Анна Собственник",
      sentAt: offsetDate(now, -2),
      nextTouchAt: offsetDate(now, 2),
      fileUrl: "/uploads/proposals/seed-kp.pdf",
      fileName: "seed-kp.pdf",
      fileSize: 29,
      fileMimeType: "application/pdf",
      uploadedById: "seed_owner",
      uploadedAt: now,
      declineReason: null,
      declineComment: null,
      comment: "Seed КП для проверки отправки и follow-up",
      archivedAt: null,
      notes: "Seed КП для проверки отправки и follow-up"
    },
    create: {
      id: "seed_proposal_sanitary_v1",
      proposalNumber: `КП-${year}-0001`,
      dealId: "seed_deal_apartments_sanitary",
      clientId: "seed_client_showroom",
      objectId: "seed_project_object_apartments",
      designerId: "seed_designer_north",
      responsibleId: "seed_owner",
      version: 1,
      parentProposalId: null,
      amount: 1850000,
      discountPercent: 7,
      discountAmount: 139250,
      status: "SENT",
      recipientType: "CLIENT",
      recipientName: "Клиент шоурума",
      recipientContact: "client@example.com",
      approvalRequiredFrom: "Анна Собственник",
      sentAt: offsetDate(now, -2),
      nextTouchAt: offsetDate(now, 2),
      fileUrl: "/uploads/proposals/seed-kp.pdf",
      fileName: "seed-kp.pdf",
      fileSize: 29,
      fileMimeType: "application/pdf",
      uploadedById: "seed_owner",
      uploadedAt: now,
      declineReason: null,
      declineComment: null,
      comment: "Seed КП для проверки отправки и follow-up",
      createdById: "seed_owner",
      archivedAt: null,
      notes: "Seed КП для проверки отправки и follow-up"
    }
  });

  await prisma.commercialProposal.upsert({
    where: { id: "seed_proposal_sanitary_v2" },
    update: {
      proposalNumber: `КП-${year}-0002`,
      dealId: "seed_deal_apartments_sanitary",
      clientId: "seed_client_showroom",
      objectId: "seed_project_object_apartments",
      designerId: "seed_designer_north",
      responsibleId: "seed_owner",
      version: 2,
      parentProposalId: "seed_proposal_sanitary_v1",
      amount: 2200000,
      discountPercent: 5,
      discountAmount: 115000,
      status: "CLIENT_THINKING",
      recipientType: "CLIENT",
      recipientName: "Клиент шоурума",
      recipientContact: "client@example.com",
      approvalRequiredFrom: "Анна Собственник",
      sentAt: offsetDate(now, -8),
      nextTouchAt: offsetDate(now, -1),
      fileUrl: "/uploads/proposals/seed-kp.pdf",
      fileName: "seed-kp.pdf",
      fileSize: 29,
      fileMimeType: "application/pdf",
      uploadedById: "seed_owner",
      uploadedAt: now,
      declineReason: null,
      declineComment: null,
      comment: "Seed версия КП: клиент думает больше 7 дней",
      archivedAt: null,
      notes: "Seed версия КП: клиент думает больше 7 дней"
    },
    create: {
      id: "seed_proposal_sanitary_v2",
      proposalNumber: `КП-${year}-0002`,
      dealId: "seed_deal_apartments_sanitary",
      clientId: "seed_client_showroom",
      objectId: "seed_project_object_apartments",
      designerId: "seed_designer_north",
      responsibleId: "seed_owner",
      version: 2,
      parentProposalId: "seed_proposal_sanitary_v1",
      amount: 2200000,
      discountPercent: 5,
      discountAmount: 115000,
      status: "CLIENT_THINKING",
      recipientType: "CLIENT",
      recipientName: "Клиент шоурума",
      recipientContact: "client@example.com",
      approvalRequiredFrom: "Анна Собственник",
      sentAt: offsetDate(now, -8),
      nextTouchAt: offsetDate(now, -1),
      fileUrl: "/uploads/proposals/seed-kp.pdf",
      fileName: "seed-kp.pdf",
      fileSize: 29,
      fileMimeType: "application/pdf",
      uploadedById: "seed_owner",
      uploadedAt: now,
      declineReason: null,
      declineComment: null,
      comment: "Seed версия КП: клиент думает больше 7 дней",
      createdById: "seed_owner",
      archivedAt: null,
      notes: "Seed версия КП: клиент думает больше 7 дней"
    }
  });

  await prisma.commercialProposal.upsert({
    where: { id: "seed_proposal_accessories_declined" },
    update: {
      proposalNumber: `КП-${year}-0003`,
      dealId: "seed_deal_apartments_accessories_lost",
      clientId: "seed_client_showroom",
      objectId: "seed_project_object_apartments",
      designerId: "seed_designer_north",
      responsibleId: "seed_sales_lead",
      version: 1,
      parentProposalId: null,
      amount: 320000,
      discountPercent: null,
      discountAmount: null,
      status: "DECLINED",
      recipientType: "CLIENT",
      recipientName: "Клиент шоурума",
      recipientContact: "client@example.com",
      approvalRequiredFrom: null,
      sentAt: offsetDate(now, -4),
      nextTouchAt: null,
      fileUrl: "/uploads/proposals/seed-kp.pdf",
      fileName: "seed-kp.pdf",
      fileSize: 29,
      fileMimeType: "application/pdf",
      uploadedById: "seed_sales_lead",
      uploadedAt: now,
      declineReason: "PRICE",
      declineComment: "Клиент выбрал более дешевый комплект",
      comment: "Seed отклоненное КП",
      archivedAt: null,
      notes: "Seed отклоненное КП"
    },
    create: {
      id: "seed_proposal_accessories_declined",
      proposalNumber: `КП-${year}-0003`,
      dealId: "seed_deal_apartments_accessories_lost",
      clientId: "seed_client_showroom",
      objectId: "seed_project_object_apartments",
      designerId: "seed_designer_north",
      responsibleId: "seed_sales_lead",
      version: 1,
      parentProposalId: null,
      amount: 320000,
      discountPercent: null,
      discountAmount: null,
      status: "DECLINED",
      recipientType: "CLIENT",
      recipientName: "Клиент шоурума",
      recipientContact: "client@example.com",
      approvalRequiredFrom: null,
      sentAt: offsetDate(now, -4),
      nextTouchAt: null,
      fileUrl: "/uploads/proposals/seed-kp.pdf",
      fileName: "seed-kp.pdf",
      fileSize: 29,
      fileMimeType: "application/pdf",
      uploadedById: "seed_sales_lead",
      uploadedAt: now,
      declineReason: "PRICE",
      declineComment: "Клиент выбрал более дешевый комплект",
      comment: "Seed отклоненное КП",
      createdById: "seed_owner",
      archivedAt: null,
      notes: "Seed отклоненное КП"
    }
  });


}
